"""Maya connection bootstrap guide.

Provides automated setup and fallback instructions for establishing
the Maya command port connection. Handles platform differences
(Windows/Linux/macOS) and Maya version detection.

Key responsibilities:
1. Generate userSetup.py content for auto-opening command port
2. Detect Maya installation paths per platform
3. Provide human-readable fallback instructions when auto-setup fails
4. Diagnose connection issues and suggest fixes
"""

from __future__ import annotations

import logging
import os
import platform
from dataclasses import dataclass
from pathlib import Path
from typing import Any


logger = logging.getLogger(__name__)

# Default command port
DEFAULT_COMMAND_PORT = 7001

# Maya version year ranges we support
SUPPORTED_MAYA_VERSIONS = [2020, 2022, 2023, 2024, 2025]

# userSetup.py template — opens command port on Maya startup
USER_SETUP_TEMPLATE = '''\
# Maya MCP Server — Auto Command Port Setup
# Place this file in Maya's scripts directory to auto-open the command port.
# Generated by maya-mcp-server connection_guide module.
#
# File locations:
#   Windows:  %MAYA_APP_DIR%/<version>/scripts/userSetup.py
#   Linux:    ~/maya/<version>/scripts/userSetup.py
#   macOS:    ~/Library/Preferences/Autodesk/maya/<version>/scripts/userSetup.py

import maya.cmds as cmds
import sys

_PORT = {port}
_SOURCE_TYPE = "python"

def _open_command_port():
    """Open Maya command port for MCP server connection."""
    try:
        # Check if port is already open
        existing = cmds.commandPort(query=True, listPorts=True) or []
        port_str = f":{{_PORT}}"
        for p in existing:
            if str(_PORT) in str(p):
                # Port already open
                return True
        cmds.commandPort(name=port_str, sourceType=_SOURCE_TYPE)
        print(f"[MCP] Command port {{_PORT}} opened successfully")
        return True
    except Exception as e:
        print(f"[MCP] Warning: Could not open command port {{_PORT}}: {{e}}")
        print(f"[MCP] Manual fix: run in Script Editor (Python):")
        print(f'[MCP]   import maya.cmds as cmds; cmds.commandPort(name=":{{_PORT}}", sourceType="python")')
        return False

# Use evalDeferred to ensure Maya is fully initialized before opening port
try:
    cmds.evalDeferred("_open_command_port()", lowestPriority=True)
except Exception:
    # Fallback: try immediately (older Maya versions)
    _open_command_port()
'''


@dataclass
class MayaInstallInfo:
    """Detected Maya installation information."""

    version: str
    scripts_dir: Path
    user_setup_path: Path
    platform: str
    maya_app_dir: str | None
    is_valid: bool
    notes: list[str]


def _get_platform() -> str:
    """Get normalized platform name."""
    system = platform.system().lower()
    if system == "windows":
        return "windows"
    elif system == "linux":
        return "linux"
    elif system == "darwin":
        return "macos"
    return system


def _get_maya_app_dir() -> str | None:
    """Get MAYA_APP_DIR environment variable."""
    return os.environ.get("MAYA_APP_DIR")


def _find_maya_versions_windows() -> list[MayaInstallInfo]:
    """Find Maya installations on Windows."""
    results: list[MayaInstallInfo] = []
    maya_app_dir = _get_maya_app_dir()

    # Check MAYA_APP_DIR first
    if maya_app_dir:
        for ver in SUPPORTED_MAYA_VERSIONS:
            scripts_dir = Path(maya_app_dir) / str(ver) / "scripts"
            if scripts_dir.exists():
                results.append(MayaInstallInfo(
                    version=str(ver),
                    scripts_dir=scripts_dir,
                    user_setup_path=scripts_dir / "userSetup.py",
                    platform="windows",
                    maya_app_dir=maya_app_dir,
                    is_valid=True,
                    notes=[f"MAYA_APP_DIR={maya_app_dir}"],
                ))

    # Check common Windows locations
    common_roots = [
        Path(os.environ.get("USERPROFILE", "")) / "Documents" / "maya",
        Path("C:/Users") / os.environ.get("USERNAME", "") / "Documents" / "maya",
        Path(os.environ.get("LOCALAPPDATA", "")) / "Autodesk" / "Maya",
    ]

    # Also check user's custom MAYA_APP_DIR paths
    for root in common_roots:
        if not root.exists():
            continue
        for ver in SUPPORTED_MAYA_VERSIONS:
            scripts_dir = root / str(ver) / "scripts"
            if scripts_dir.exists() and not any(
                r.scripts_dir == scripts_dir for r in results
            ):
                results.append(MayaInstallInfo(
                    version=str(ver),
                    scripts_dir=scripts_dir,
                    user_setup_path=scripts_dir / "userSetup.py",
                    platform="windows",
                    maya_app_dir=str(root),
                    is_valid=True,
                    notes=[f"Found at {scripts_dir}"],
                ))

    return results


def _find_maya_versions_linux() -> list[MayaInstallInfo]:
    """Find Maya installations on Linux."""
    results: list[MayaInstallInfo] = []
    home = Path.home()

    for ver in SUPPORTED_MAYA_VERSIONS:
        scripts_dir = home / "maya" / str(ver) / "scripts"
        if scripts_dir.exists():
            results.append(MayaInstallInfo(
                version=str(ver),
                scripts_dir=scripts_dir,
                user_setup_path= scripts_dir / "userSetup.py",
                platform="linux",
                maya_app_dir=str(home / "maya"),
                is_valid=True,
                notes=[f"Standard Linux path: {scripts_dir}"],
            ))

    # Check MAYA_APP_DIR override
    maya_app_dir = _get_maya_app_dir()
    if maya_app_dir:
        for ver in SUPPORTED_MAYA_VERSIONS:
            scripts_dir = Path(maya_app_dir) / str(ver) / "scripts"
            if scripts_dir.exists() and not any(
                r.scripts_dir == scripts_dir for r in results
            ):
                results.append(MayaInstallInfo(
                    version=str(ver),
                    scripts_dir=scripts_dir,
                    user_setup_path=scripts_dir / "userSetup.py",
                    platform="linux",
                    maya_app_dir=maya_app_dir,
                    is_valid=True,
                    notes=[f"MAYA_APP_DIR={maya_app_dir}"],
                ))

    return results


def _find_maya_versions_macos() -> list[MayaInstallInfo]:
    """Find Maya installations on macOS."""
    results: list[MayaInstallInfo] = []
    home = Path.home()

    for ver in SUPPORTED_MAYA_VERSIONS:
        scripts_dir = home / "Library" / "Preferences" / "Autodesk" / "maya" / str(ver) / "scripts"
        if scripts_dir.exists():
            results.append(MayaInstallInfo(
                version=str(ver),
                scripts_dir=scripts_dir,
                user_setup_path=scripts_dir / "userSetup.py",
                platform="macos",
                maya_app_dir=str(home / "Library" / "Preferences" / "Autodesk" / "maya"),
                is_valid=True,
                notes=[f"macOS standard path: {scripts_dir}"],
            ))

    return results


def find_maya_installations() -> list[MayaInstallInfo]:
    """Find all Maya installations on the current platform.

    Returns:
        List of detected Maya installation info objects.
    """
    system = _get_platform()
    if system == "windows":
        return _find_maya_versions_windows()
    elif system == "linux":
        return _find_maya_versions_linux()
    elif system == "macos":
        return _find_maya_versions_macos()
    return []


def generate_user_setup_content(port: int = DEFAULT_COMMAND_PORT) -> str:
    """Generate userSetup.py content for the given port.

    Args:
        port: Maya command port number.

    Returns:
        Python source code for userSetup.py.
    """
    return USER_SETUP_TEMPLATE.format(port=port)


def install_user_setup(
    port: int = DEFAULT_COMMAND_PORT,
    target_version: str | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Install userSetup.py to Maya scripts directories.

    Args:
        port: Command port number.
        target_version: Specific Maya version to target (e.g., "2024").
            If None, installs to all detected versions.
        dry_run: If True, only report what would be done.

    Returns:
        Dict with installation results and diagnostics.
    """
    installations = find_maya_installations()
    if not installations:
        return {
            "success": False,
            "error": "No Maya installations found",
            "diagnostics": get_connection_diagnostics(port),
        }

    if target_version:
        installations = [i for i in installations if i.version == target_version]
        if not installations:
            return {
                "success": False,
                "error": f"Maya version {target_version} not found",
                "available_versions": [i.version for i in find_maya_installations()],
            }

    content = generate_user_setup_content(port)
    results: list[dict[str, Any]] = []

    for install in installations:
        target_path = install.user_setup_path
        entry = {
            "version": install.version,
            "path": str(target_path),
            "action": "none",
        }

        if dry_run:
            if target_path.exists():
                entry["action"] = "would_overwrite"
            else:
                entry["action"] = "would_create"
            results.append(entry)
            continue

        try:
            # Backup existing file
            if target_path.exists():
                backup = target_path.with_suffix(".py.bak")
                backup.write_text(target_path.read_text(encoding="utf-8"), encoding="utf-8")
                entry["backup"] = str(backup)
                entry["action"] = "overwritten"
            else:
                entry["action"] = "created"

            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(content, encoding="utf-8")
            entry["success"] = True

        except OSError as e:
            entry["success"] = False
            entry["error"] = str(e)
            entry["action"] = "failed"

        results.append(entry)

    return {
        "success": any(r.get("success", False) for r in results) or dry_run,
        "results": results,
        "instructions": get_fallback_instructions(port),
    }


def get_fallback_instructions(port: int = DEFAULT_COMMAND_PORT) -> str:
    """Get human-readable fallback instructions for manual command port setup.

    This is used when userSetup.py doesn't work or when the user needs
    to manually open the command port.

    Args:
        port: Command port number.

    Returns:
        Step-by-step instructions in the user's context.
    """
    system = _get_platform()

    instructions = f"""## Maya MCP 连接引导 / Maya MCP Connection Guide

### 方式一：自动配置（推荐 / Option A: Auto-Setup (Recommended))

已生成 `userSetup.py` 文件，放置在 Maya 的 scripts 目录下。
重启 Maya 后，命令端口将自动打开。

Generated `userSetup.py` has been placed in Maya's scripts directory.
Restart Maya and the command port will open automatically.

### 方式二：手动配置 / Option B: Manual Setup

如果自动配置不生效，请按以下步骤手动操作：

**步骤 1：打开 Maya Script Editor**
1. 打开 Maya
2. 菜单栏 → Windows → General Editors → Script Editor
   (或底部状态栏点击 Script Editor 图标)

**步骤 2：选择 Python 模式**
在 Script Editor 底部，确认语言选择器显示为 **Python**（不是 MEL）。
如果显示 MEL，点击切换为 Python。

**步骤 3：输入并执行以下代码**

```python
import maya.cmds as cmds
cmds.commandPort(name=":{port}", sourceType="python")
```

选中上述代码，按 **Ctrl+Enter**（或数字键盘 Enter）执行。

**步骤 4：验证端口已打开**

```python
print(cmds.commandPort(query=True, listPorts=True))
```

应显示包含 `":{port}"` 的列表。

### 常见问题排查 / Troubleshooting

1. **端口被占用**: 关闭其他 Maya 实例，或换一个端口号
2. **防火墙阻止**: 确保本地防火墙允许 Maya 监听 localhost:{port}
3. **userSetup.py 未执行**: 确认文件放在正确的 scripts 目录下（见下方路径说明）

### 各平台 scripts 目录路径

"""

    if system == "windows":
        instructions += f"""**Windows:**
- `%MAYA_APP_DIR%\\<version>\\scripts\\userSetup.py`
- `C:\\Users\\<username>\\Documents\\maya\\<version>\\scripts\\userSetup.py`
- 自定义: 如果设置了 `MAYA_APP_DIR` 环境变量，使用该变量指向的路径

例如 Maya 2024:
- `%MAYA_APP_DIR%\\2024\\scripts\\userSetup.py`
- `C:\\Users\\Administrator\\Documents\\maya\\2024\\scripts\\userSetup.py`
"""
    elif system == "linux":
        instructions += f"""**Linux:**
- `~/maya/<version>/scripts/userSetup.py`

例如 Maya 2024:
- `~/maya/2024/scripts/userSetup.py`

注意: Maya on Linux 需要通过 Autodesk 官方安装或 Flatpak。
"""
    elif system == "macos":
        instructions += f"""**macOS:**
- `~/Library/Preferences/Autodesk/maya/<version>/scripts/userSetup.py`

例如 Maya 2024:
- `~/Library/Preferences/Autodesk/maya/2024/scripts/userSetup.py`
"""

    instructions += f"""
### 环境变量说明

- `MAYA_APP_DIR`: Maya 的用户配置根目录。如果设置了此变量，Maya 会在此目录下查找 scripts。
- 可在系统环境变量中设置，也可在 Maya 安装目录的 `Maya.env` 文件中设置。

### 连接端口配置

默认端口: `{port}`
如需更改端口，修改 userSetup.py 中的 `_PORT` 值，并同步修改 MCP 服务器配置。
"""

    return instructions


def get_connection_diagnostics(port: int = DEFAULT_COMMAND_PORT) -> dict[str, Any]:
    """Diagnose connection issues and provide actionable suggestions.

    Args:
        port: Command port to diagnose.

    Returns:
        Diagnostic results with issues and suggestions.
    """
    diagnostics: dict[str, Any] = {
        "platform": _get_platform(),
        "port": port,
        "maya_running": False,
        "port_open": False,
        "user_setup_found": [],
        "issues": [],
        "suggestions": [],
    }

    # Check if Maya is running
    try:
        import psutil
        for proc in psutil.process_iter(["name"]):
            try:
                name = proc.info.get("name", "")
                if name and name.lower() in ("maya", "maya.exe"):
                    diagnostics["maya_running"] = True
                    break
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                continue
    except ImportError:
        diagnostics["issues"].append("psutil not available — cannot detect Maya process")

    # Check if port is listening
    try:
        import socket
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1.0)
            result = s.connect_ex(("127.0.0.1", port))
            diagnostics["port_open"] = result == 0
    except OSError as e:
        diagnostics["issues"].append(f"Socket check failed: {e}")

    # Check for userSetup.py
    installations = find_maya_installations()
    for install in installations:
        if install.user_setup_path.exists():
            diagnostics["user_setup_found"].append({
                "version": install.version,
                "path": str(install.user_setup_path),
            })

    # Generate issues and suggestions
    if not diagnostics["maya_running"]:
        diagnostics["issues"].append("Maya 未运行 / Maya is not running")
        diagnostics["suggestions"].append("请先启动 Maya / Please start Maya first")

    if diagnostics["maya_running"] and not diagnostics["port_open"]:
        diagnostics["issues"].append(
            f"Maya 正在运行但端口 {port} 未打开 / "
            f"Maya is running but port {port} is not open"
        )
        if not diagnostics["user_setup_found"]:
            diagnostics["suggestions"].append(
                f"未找到 userSetup.py，请运行安装引导 / "
                f"No userSetup.py found. Run the connection guide to install it."
            )
        else:
            diagnostics["suggestions"].append(
                "userSetup.py 已存在但端口未打开，可能需要重启 Maya / "
                "userSetup.py exists but port not open, Maya restart may be needed"
            )
            diagnostics["suggestions"].append(
                f"或者手动在 Script Editor 中执行: "
                f'cmds.commandPort(name=":{port}", sourceType="python")'
            )

    if diagnostics["port_open"]:
        diagnostics["suggestions"].append(
            f"端口 {port} 已打开，可以连接 / Port {port} is open, ready to connect"
        )

    return diagnostics


def get_agent_connection_instructions(port: int = DEFAULT_COMMAND_PORT) -> str:
    """Get instructions for the AI agent to guide the user through connection setup.

    This is the main entry point for agent-facing guidance. The agent should
    use these instructions when:
    1. list_sessions returns empty
    2. Connection to Maya fails
    3. User asks how to set up Maya MCP

    Args:
        port: Command port number.

    Returns:
        Structured instructions for the agent to relay to the user.
    """
    diagnostics = get_connection_diagnostics(port)
    system = diagnostics["platform"]

    agent_guide = f"""# Maya MCP 连接诊断 / Connection Diagnostics

## 当前状态

- 平台: {system}
- 目标端口: {port}
- Maya 运行: {"✅ 是" if diagnostics["maya_running"] else "❌ 否"}
- 端口监听: {"✅ 已打开" if diagnostics["port_open"] else "❌ 未打开"}
- userSetup.py: {"✅ 已找到" if diagnostics["user_setup_found"] else "❌ 未找到"}
"""

    if diagnostics["user_setup_found"]:
        for found in diagnostics["user_setup_found"]:
            agent_guide += f"  - Maya {found['version']}: {found['path']}\n"

    if diagnostics["issues"]:
        agent_guide += "\n## 发现的问题\n\n"
        for issue in diagnostics["issues"]:
            agent_guide += f"- {issue}\n"

    if diagnostics["suggestions"]:
        agent_guide += "\n## 建议操作\n\n"
        for i, suggestion in enumerate(diagnostics["suggestions"], 1):
            agent_guide += f"{i}. {suggestion}\n"

    # Add platform-specific manual instructions
    if not diagnostics["port_open"]:
        agent_guide += f"""
## 手动开启端口指引 / Manual Port Opening Guide

请让用户在 Maya 中执行以下操作：

### 步骤 1：打开 Script Editor
"""
        if system == "windows":
            agent_guide += """在 Maya 菜单栏: Windows → General Editors → Script Editor
或按快捷键: 无默认快捷键，可从底部状态栏点击图标
"""
        elif system == "linux":
            agent_guide += """在 Maya 菜单栏: Windows → General Editors → Script Editor
"""
        elif system == "macos":
            agent_guide += """在 Maya 菜单栏: Windows → General Editors → Script Editor
"""

        agent_guide += f"""
### 步骤 2：切换到 Python 模式
Script Editor 底部有语言选择器，确保显示为 **Python**（不是 MEL）

### 步骤 3：输入并执行代码
```python
import maya.cmds as cmds
cmds.commandPort(name=":{port}", sourceType="python")
```
选中代码后按 Ctrl+Enter 执行。

### 步骤 4：验证
执行后再次调用 `list_sessions` 检查连接。
"""

    # Auto-install offer
    if not diagnostics["user_setup_found"] and not diagnostics["port_open"]:
        agent_guide += """
## 自动安装 userSetup.py

如果用户同意，可以运行以下命令自动安装 userSetup.py 到 Maya scripts 目录：

```bash
python -m maya_mcp_server.connection_guide install
```

或者通过 MCP 工具 `maya_setup_guide` 获取完整引导。
"""

    return agent_guide


def uninstall_user_setup(
    port: int = DEFAULT_COMMAND_PORT,
    target_version: str | None = None,
) -> dict[str, Any]:
    """Remove installed userSetup.py from Maya scripts directories.

    Args:
        port: Command port number (unused but kept for API consistency).
        target_version: Specific Maya version. If None, removes from all.

    Returns:
        Dict with removal results.
    """
    installations = find_maya_installations()
    if target_version:
        installations = [i for i in installations if i.version == target_version]

    results = []
    for install in installations:
        target_path = install.user_setup_path
        entry = {
            "version": install.version,
            "path": str(target_path),
            "action": "none",
        }
        if target_path.exists():
            try:
                target_path.unlink()
                entry["action"] = "removed"
                entry["success"] = True
            except OSError as e:
                entry["action"] = "failed"
                entry["success"] = False
                entry["error"] = str(e)
        else:
            entry["action"] = "not_found"
        results.append(entry)

    return {
        "success": any(r.get("success", False) for r in results),
        "results": results,
    }

